.\" Copyright (c) 2021 Tim van der Molen <tim@kariliq.nl>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd January 19, 2025
.Dt SIGTOP 1
.Os
.Sh NAME
.Nm sigtop
.Nd export messages from Signal Desktop
.Sh SYNOPSIS
.Nm sigtop
.Ar command
.Op Ar argument ...
.Sh DESCRIPTION
.Nm
is a utility to export messages, attachments and other data from Signal
Desktop.
.Pp
.Nm
needs access to the directory where Signal Desktop stores its data.
By default,
.Nm
tries the following locations:
.Bl -tag -width "Windows"
.It Windows
.Pa %AppData%\eSignal
.It macOS
.Pa "$HOME/Library/Application Support/Signal"
.It Unix
.Pa $XDG_CONFIG_HOME/Signal ,
or
.Pa $HOME/.config/Signal
if
.Ev XDG_CONFIG_HOME
is unset or empty.
If neither directory exists,
.Nm
tries the locations used by the unofficial Snap and Flatpak versions of Signal
Desktop.
These locations are
.Pa $HOME/snap/signal-desktop/current/.config/Signal
and
.Pa $HOME/.var/app/org.signal.Signal/config/Signal ,
respectively.
.El
.Pp
A different location for the Signal Desktop directory can be specified using
the
.Fl d
option (see below).
.Pp
To use
.Nm
with Signal Desktop Beta, use the
.Fl B
option (see below).
With this option,
.Nm
uses the encryption key and default directory locations for Signal Desktop
Beta.
The directory location can still be overridden with
.Fl d .
.Pp
The commands are as follows:
.Bl -tag -width Ds
.Tg check
.It Xo
.Ic check-database
.Op Fl B
.Op Fl d Ar signal-directory
.Xc
.D1 Pq Alias: Ic check
.Pp
Check the integrity of the encrypted Signal Desktop database.
The check is performed using the SQLite/SQLCipher
.Cm cipher_integrity_check ,
.Cm integrity_check
and
.Cm foreign_key_check
pragmas.
.Tg att
.It Xo
.Ic export-attachments
.Op Fl BiMm
.Op Fl c Ar conversation
.Op Fl d Ar signal-directory
.Op Fl s Ar interval
.Op Ar directory
.Xc
.D1 Pq Alias: Ic att
.Pp
Export attachments.
The attachment files are created in separate directories, one for each
conversation.
These directories are created in
.Ar directory ,
or in the current directory if
.Ar directory
is not specified.
.Pp
If
.Fl M
is specified, the file modification time of each exported attachment is set to
the time the attachment was sent.
The
.Fl m
option is similar, but uses the time the attachment was received.
.Pp
If
.Fl i
is specified, an incremental export is performed.
This means that only new attachments are exported; attachments that were
exported in a previous run are skipped.
The
.Pa .incremental
file in
.Pa directory
is used to keep track of exported attachments.
.Pp
If
.Fl c
is specified, only the attachments from the specified conversation are
exported.
The
.Fl c
option can be specified multiple times to specify multiple conversations.
See the
.Sx CONVERSATION SELECTORS
section below for details.
.Pp
If
.Fl s
is specified, only the attachments that were sent in the specified time
interval are exported.
See the
.Sx TIME INTERVALS
section below for details.
.Tg avt
.It Xo
.Ic export-avatars
.Op Fl B
.Op Fl c Ar conversation
.Op Fl d Ar signal-directory
.Op Ar directory
.Xc
.D1 Pq Alias: Ic avt
.Pp
Export avatars.
The avatar files are created in
.Ar directory ,
or in the current directory if
.Ar directory
is not specified.
.Pp
If
.Fl c
is specified, only the avatar from the specified conversation is exported.
The
.Fl c
option can be specified multiple times to specify multiple conversations.
See the
.Sx CONVERSATION SELECTORS
section below for details.
.Tg db
.It Xo
.Ic export-database
.Op Fl B
.Op Fl d Ar signal-directory
.Ar file
.Xc
.D1 Pq Alias: Ic db
.Pp
Decrypt and export the Signal Desktop database to
.Ar file .
The exported database is a regular SQLite database.
.Tg key
.It Xo
.Ic export-key
.Op Fl BD
.Op Fl d Ar signal-directory
.Op Ar file
.Xc
.D1 Pq Alias: Ic key
.Pp
Export the encryption key that is needed to decrypt the database key.
The key is written to
.Ar file ,
or to standard output if
.Ar file
is not specified.
.Pp
If
.Fl D
is specified, the database key is exported instead of the encryption key.
.Tg msg
.It Xo
.Ic export-messages
.Op Fl Bi
.Op Fl c Ar conversation
.Op Fl d Ar signal-directory
.Op Fl f Ar format
.Op Fl s Ar interval
.Op Ar directory
.Xc
.D1 Pq Alias: Ic msg
.Pp
Export messages.
The messages are written to separate files, one for each conversation.
These files are created in
.Ar directory ,
or in the current directory if
.Ar directory
is not specified.
.Pp
The
.Fl f
option may be used to specify the output format.
The following output formats are supported:
.Bl -tag -width "text-short"
.It Cm json
Messages are written in JSON format.
The JSON data is copied directly from the Signal Desktop database, so its
structure may differ between Signal Desktop versions.
.It Cm text
Messages are written as plain text.
This is the default.
.It Cm text-short
Messages are written as plain text, in short form.
Every message is written on a single line.
.El
.Pp
By default,
existing files in
.Pa directory
are not overwritten.
If
.Fl i
is specified, an incremental export is performed.
This means that existing conversation files are updated.
.Pp
If
.Fl c
is specified, only the messages from the specified conversation are exported.
The
.Fl c
option can be specified multiple times to specify multiple conversations.
See the
.Sx CONVERSATION SELECTORS
section below for details.
.Pp
If
.Fl s
is specified, only the messages that were sent in the specified time interval
are exported.
See the
.Sx TIME INTERVALS
section below for details.
.Tg query
.It Xo
.Ic query-database
.Op Fl B
.Op Fl d Ar signal-directory
.Op Fl o Ar outfile
.Ar sql
.Xc
.D1 Pq Alias: Ic query
.Pp
Query the Signal Desktop database.
The results of the query, if any, are written to
.Ar outfile ,
or to standard output if
.Ar outfile
is not specified.
Because the Signal Desktop database is opened in read-only mode, statements
attempting to modify the database will fail.
.El
.Sh CONVERSATION SELECTORS
Conversation selectors select conversations by name, phone number, service ID
or group ID.
Names can be matched either literally or against a regular expression.
A service ID is a UUID that uniquely identifies a Signal user.
.Pp
A conversation selector of the form
.Sq Cm = Ns Ar name
selects every conversation with the specified name.
Names are matched case-insensitively.
The prefix
.Cm =
may be omitted if
.Ar name
does not begin with
.Sq = ,
.Sq / ,
.Sq +
or
.Sq \&: .
For example, the conversation selectors
.Ql =alice
and
.Ql alice
each match the conversation with Alice.
.Pp
A conversation selector of the form
.Sq Cm / Ns Ar regex
selects every conversation whose name is matched by the regular expression
.Ar regex .
Names are matched case-insensitively.
.Pp
A conversation selector that starts with
.Sq +
selects a conversation by phone number.
For example, the conversation selector
.Ql +123456789
matches the conversation with that phone number.
.Pp
A conversation selector of the form
.Sq Cm \&: Ns Ar id
selects a conversation based on an ID.
If
.Ar id
is a service ID, it selects the conversation with the Signal user with that
service ID.
If
.Ar id
is a group ID, it selects the conversation from the group with that group ID.
.Sh TIME INTERVALS
A time is specified as
.So
.Sm off
.Ar yyyy
.Oo Cm - Ar mm
.Oo Cm - Ar dd
.Oo Cm T Ar hh
.Oo Cm \&: Ar mm
.Oo Cm \&: Ar ss
.Oc Oc Oc Oc Oc
.Sm on
.Sc .
For example:
.Bd -literal -offset indent
2023-01-23T12:34:56
2023-01-23T12:34
2023-01
2023
.Ed
.Pp
A time interval is specified either as
.So
.Sm off
.Op Ar min-time
.Cm \&,
.Op Ar max-time
.Sm on
.Sc
or as
.Sq Ar time .
In the first form,
.Ar min-time
and
.Ar max-time
are the endpoints of the time interval.
The endpoints are inclusive.
.Pp
Each omitted time field in
.Ar min-time
defaults to the smallest possible value for that time field.
Analogously, each omitted time field in
.Ar max-time
defaults to the largest possible value for that time field.
For example, the interval
.Ql 2023-02,2023
is equivalent to:
.Bd -literal -offset indent
2023-02-01T00:00:00,2023-12-31T23:59:59
.Ed
.Pp
Furthermore, either endpoint of the time interval may be omitted.
For example, the interval from the start of February 2023 to now may be
specified as
.Ql 2023-02\&, .
.Pp
Time intervals may also be specified in a second form, consisting of a single
time specification.
In this form, the same time specification is used for both endpoints.
For example, the time interval
.Ql 2023
is equivalent to
.Ql 2023,2023 ,
which is equivalent to:
.Bd -literal -offset indent
2023-01-01T00:00:00,2023-12-31T23:59:59
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Export all messages to the directory
.Pa messages :
.Bd -literal -offset indent
$ sigtop export-messages messages
.Ed
.Pp
Use the shorter command alias:
.Bd -literal -offset indent
$ sigtop msg messages
.Ed
.Pp
Export all messages in JSON format:
.Bd -literal -offset indent
$ sigtop msg -f json
.Ed
.Pp
Export the messages from the conversations with Alice and Bob:
.Bd -literal -offset indent
$ sigtop msg -c alice -c bob
.Ed
.Pp
Export all attachments sent from February 2021 onwards:
.Bd -literal -offset indent
$ sigtop att -s 2021-02,
.Ed
.Pp
Export all attachments from the conversation with the person who has phone
number +123456789:
.Bd -literal -offset indent
$ sigtop att -c +123456789
.Ed
.Pp
Export the database from a Signal Desktop directory on a Windows disk mounted
at
.Pa /mnt .
Use the encryption key from
.Pa keyfile :
.Bd -literal -offset indent
$ sigtop db -d /mnt/Users/Alice/AppData/Roaming/Signal -k windows:keyfile signal.db
.Ed
.Pp
Export the database from Signal Desktop Beta:
.Bd -literal -offset indent
$ sigtop db -B signal-beta.db
.Ed
.Sh SEE ALSO
.Lk https://github.com/tbvdm/sigtop
.Sh AUTHORS
The
.Nm
utility was written by
.An Tim van der Molen Aq Mt tim@kariliq.nl .
